---
# tasks file for ansible-role-ospfd

- name: Create ospfd.conf
  template:
    src: ospfd.conf.j2
    dest: "{{ ospfd_conf_file }}"
    mode: 0600
  notify: Restart ospfd

- name: Start ospfd
  service:
    name: "{{ ospfd_service }}"
    enabled: true
    state: started
